apiVersion: apps/v1
kind: Deployment
metadata:
  name: jagex-deployment
  labels:
    app: jagex
spec:
  selector:
    matchLabels:
      app: jagex
  template:
    metadata:
      labels:
        app: jagex
    spec:
      containers:
      - name: jagex
        image: jamflex:latest
        ports:
        - containerPort: 10000
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: jagex-service
spec:
  type: NodePort
  selector:
    app: jagex
  ports:
    - port: 80
      targetPort: 10000
      nodePort: 30000